"""TAAF worker entry — generated by TufaSlurmTarget.deploy(). Do not edit."""

import asyncio
import os
import pickle
import signal
from pathlib import Path

import taaf.benchmark  # noqa: F401
import taaf.deploy_slurm

JOB_DIR = Path('/shared/runs/20260602_112245_0-history-turns')


async def _amain(bm, soft_end, target):
    # R2.33: route SIGUSR1 (from scancel --signal=USR1) into
    # Benchmark.run's teardown by cancelling the live solver task.
    # SIGTERM (default scancel) stays as a hard kill via the default
    # python handler.
    asyncio.get_running_loop().add_signal_handler(signal.SIGUSR1, bm.request_stop)
    try:
        await bm.run(soft_end_time=soft_end, runtime_environment=target)
    except asyncio.CancelledError:
        # Teardown already wrote artifacts; swallow so the worker
        # exits 0 and sacct shows COMPLETED rather than FAILED for a
        # graceful stop.
        pass


if __name__ == "__main__":
    with open(JOB_DIR / "deploy_target.pkl", "rb") as f:
        target = pickle.load(f)

    SOFT_END = taaf.deploy_slurm.worker_soft_end_time(
        slurm_end_epoch=os.environ.get("SLURM_JOB_END_TIME"),
        max_runtime_s=getattr(target, "max_runtime_s", None),
    )

    print("benchmark.label : 0-history-turns\nbenchmark.solver: HarnessSolver(label='inference', runtime_environment=None, job_dir=None, soft_end_time=None, minimal_diagnostics=False, model='vrfai/Qwen3.6-27B-FP8', analyzer_timeout=120.0, max_actions_per_game=None, max_runtime_s_per_game=2700.0, concurrency=64, save_request_logs=False, start_local_server=True, local_server_config='configs/inference.json', local_server_api_key_file='/shared/runs/20260602_112245_0-history-turns/server-api-key', local_server_repo_dir='/shared/runs/20260602_112245_0-history-turns/src/ARC3-Inference', local_server_port=39703, local_server_tensor_parallel_size=1, local_server_count=2, cancel_drain_timeout_s=120.0)\nbenchmark.passes: 20\nbenchmark.games : 25\ngit status:\n  tufa-arc-agi-framework           fb601d7     DIRTY  main                      Merge pull request #24 from Tufalabs/feat/kaggle_integration\n  re-arc-3                         4dcacba     clean  official_description      chore: remove pipeline ablation support\n  ARC3-Inference                   dd50b55     DIRTY  user/periodic-chat-clearing  Make history turn cap configurable, default to unlimited")
    print(f"deploy.slurm: job_dir       = {JOB_DIR}")
    print(f"deploy.slurm: SLURM_JOB_ID  = {os.environ.get('SLURM_JOB_ID', '?')}")
    print(f"deploy.slurm: soft_end_time = {SOFT_END}")
    print("---")

    with open(JOB_DIR / "benchmark_initial.pkl", "rb") as f:
        bm = pickle.load(f)
    bm.job_dir = JOB_DIR
    asyncio.run(_amain(bm, SOFT_END, target))

    # Bypass interpreter shutdown's threadpool-join: any stuck
    # background thread (vLLM NCCL, C-level recv, ...) would hang the
    # slurm job in RUNNING long after the run finished. Benchmark.run's
    # finally already wrote everything; os._exit lets the OS reclaim.
    os._exit(0)
